### PR TITLE
[SEC-16683] Decouple Agentless Scanning from CSPM

### PR DESCRIPTION
**Pull request by k3nz0**
### What does this PR do?

Agentless Scanning does not require CSPM to be enabled to work correctly.
However, Agentless Scanning does require the AWS SecurityAudit policy to be installed.

In this PR we:
- Decouple Agentless Scanning from CSPM (Cloud Security Posture Management)
- Add a rule to check that resource collection is enabled when at least one Agentless Scanning option is enabled

### CODE REVIEW

**Review by jvanbrie — APPROVED** [review]

**Comment by ktmq** [comment]
please bump the version number in `aws_quickstart/version.txt`

**Review by mariagardbraga — APPROVED** [review]

**Review by jvanbrie — CHANGES_REQUESTED** [review]
We merged a pretty big change to these files, so you'll need to merge those changes in and refactor a bit. We now default to adding the SecurityAudit Policy.

**Comment by k3nz0** [comment]
Rebased and applied necessary changes to decouple Agentless from CSPM

**Review by jvanbrie — COMMENTED** [review]
Can you up the version in version.txt?

**Review by jvanbrie — APPROVED** [review]

**Pull request merged**
